### PR TITLE
Ensure the args for vex.dialog's beforeClose are identical

### PR DESCRIPTION
**Pull request by banderson**
In the previous version, the arguments for the beforeClose callback
were different depending on the call-site. This makes them consistent.

### CODE REVIEW

**Comment by banderson** [comment]
This extends #116 for consistency across multiple display options

**Comment by adamschwartz** [comment]
Shouldn’t vex dialog just be taking advantage of [vex doing this](https://github.com/HubSpot/vex/blob/7d2b04484d33c9e359e6c8c9b9af1f4ff16fbc85/coffee/vex.coffee#L147-L148) for it?

**Comment by banderson** [comment]
@adamschwartz yup, just noticed the same thing. That [last commit](https://github.com/banderson/vex/commit/158ec57f39a10b0fbf5daec88e7abcd164e54706) uses the options passed through instead of re-cloning

**Comment by adamschwartz** [comment]
Excellent.

**Pull request merged**
