### PR TITLE
Convert Coffeescript to ES6 and replace build system with Gulp

### PR DESCRIPTION
**Pull request by Setsun**
Since other libraries such as Tether and it's related extensions are moving to ES6 transpiled with Babel, Gulp and a new project directory structure, I've refactored vex to follow in suit.

Even with these changes vex should still run under the examples/build-test.html file.

This is a pretty significant change so let me know of anything that may need to be worked on if this is merged into the main project.

### CODE REVIEW

**Comment by geekjuice** [comment]
Awesome! I'll try to take a look ASAP and let you know of any changes that may need to take place (if any). :beers:

**Comment by nozpheratu** [comment]
@geekjuice Any updates? This pull seems to fix some webpack issues that I've been having. :yum:

**Comment by bbatliner** [comment]
@Setsun @nozpheratu are you still interested in switching to gulp? With the release of vex 3.0.0, we're currently using vanilla ES5 and browserify for bundling, with grunt for building. I'm totally open to switching to ES6 + babel + gulp, if you're willing to adjust your PR to the new major version.

Thank you so much!

**Comment by Setsun** [comment]
@bbatliner I'll have to check when I get home, but I would be open to adjusting this PR. Depending on how much work it is to merge, I might open up another PR.

**Comment by bbatliner** [comment]
Old and outdated at this point - if someone wants to make a new PR to switch to Gulp, go for it.

**Pull request closed without merging**
