### PR TITLE
Allow `beforeClose` callback to prevent dialog from closing by returning false

### PR DESCRIPTION
**Pull request by banderson**
@adamschwartz this is the most straightforward way I could think to
accomplish the goal for #114. 

This ensures that all behavior will be identical to before with the
one exception we want: when returning `false` from `beforeClose`,
we should prevent the dialog from closing, allowing the user to
have more granular control over that process.

Does this make sense? Did I miss anything?

Thanks again.

### CODE REVIEW

**Comment by adamschwartz** [comment]
Looks good to me. :ship:

**Comment by banderson** [comment]
Who can merge this bad boy, @also?

**Comment by adamschwartz** [comment]
If you tested it and it works, you can! :wink:

**Comment by adamschwartz** [comment]
(If you don’t have privilegs, ask @johnnagro?)

**Comment by EgoAleSum** [comment]
I'm glad I found out about this. Watch out, cause it's possibly a breaking change

**Comment by banderson** [comment]
@EgoAleSum the only way to trigger this would be to return an explicit `false` (i.e. not "falsey") from the `beforeClose` handler, which is not a documented feature as far as I can tell. Can you see a different way?

**Comment by EgoAleSum** [comment]
No, it's actually very reasonable.
However, in my code I used a `return false` in place of just a `return`. I've updated my code.

I was just suggesting to advise that this change may be breaking.

**Comment by adamschwartz** [comment]
@EgoAleSum thanks for the reminder. This will absolutely be released with the appropriate SemVer bump. Hopefully along with a few other changes (#70, fore example) this will be in `v3.x.x`.

**Pull request merged**
