### PR TITLE
Removed Compass mixin dependencies and added grunt-sass task.

### PR DESCRIPTION
**Pull request by MartijnR**
I didn't remove the grunt-contrib-compass task, in case you'd like to keep using it.

I diffed all the output files and they are the same as before (apart from comments) when building with Compass. 

When building with grunt-sass it's a bit harder to diff the files due to difference in output style, but I believe the output is the same.

### CODE REVIEW

**Comment by adamschwartz** [comment]
Thanks @MartijnR! I’ll be taking a look.

**Comment by Specialkbyte** [comment]
@MartijnR This is great I can't wait till this get's merged in. +1

**Comment by Romanx** [comment]
Yeah :+1:  here too. Was planning to do this myself before I saw the issue and related pull.

**Comment by adamschwartz** [comment]
@Specialkbyte @Romanx I hear ya’. The only thing holding this up is I haven’t yet had the time to verify that the output CSS is the same with these changes. If somebody can do that I’d be happy to merge. Otherwise it might take a little more time. Thanks!

**Comment by adamschwartz** [comment]
(Closing was an accident.)

**Comment by danieljacobarcher** [comment]
@adamschwartz Can you bump the version up? I'm trying to install Vex via rails-assets, and the 2.3.0 version doesn't have the latest Compass removals.

**Comment by adamschwartz** [comment]
Hey @danieljacobarcher. I was a little overzealous in my merges. I merged #103 and #104 at the same time as #100, and it turned out they have a few issues preventing me from releasing. To help you out, I’ll revert those (#105 and 2a7e97814c1dc365517aea57679fe2b36399e953) and release a new version with only #100 (since v2.3.0).

**Comment by danieljacobarcher** [comment]
Ok thanks! Love Vex though!

**Comment by adamschwartz** [comment]
Here you go! https://github.com/HubSpot/vex/releases/tag/v2.3.1

**Comment by danieljacobarcher** [comment]
@adamschwartz Thanks! I just updated it in rails-assets. Running into an error if I don't include vex.dialog or vex.combined, and it looks like they're not being indexed through rails-assets properly (Rails can't find vex.dialog or vex.combined). Any ideas?

If I only include vex, I get the error:
```TypeError: undefined is not an object (evaluating 'vex.dialog.prompt')
http://localhost:3000/settings/marvel```

**Comment by adamschwartz** [comment]
Sorry, I’m not familiar with `rails-assets`. @timmfin any ideas? Or perhaps @MartijnR?

**Comment by MartijnR** [comment]
I'm also not familiar with this.

**Pull request merged**
