### PR TITLE
master > Add an option for not adding vex-open class to body when opening a Vex model.

### PR DESCRIPTION
**Pull request by supernintendo**
I would like to be able to prevent adding the `vex-open` class to the body element on open. Currently, the only way to achieve this is to manually remove the class with jQuery on `afterClose` and `afterOpen` which is a bit hacky. This PR adds a Vex option called `dontPreventScroll` which, if true, prevents injecting that body class.

Thanks!

### CODE REVIEW

**Comment by supernintendo** [comment]
@adamschwartz, sorry for the late response. This PR was intended to fix the issue I was experiencing which is documented here: https://github.com/HubSpot/vex/issues/75, however overriding the CSS achieves the desired effect.

I will close this out as it seems another approach is being explored.

**Comment by adamschwartz** [comment]
@supernintendo Makes sense, thanks for the update.

Definitely working on a solution to all of #33, #43, #75, #85. Stuff gets tricky.

**Comment by 1eddy87** [comment]
Hi @adamschwartz , I was just wondering if you have found a solution to the issues you listed (#33, #43, #75, #85).

Reason I ask is  because I'm getting a weird issue on iPhone 6S (only one I have tested so far). I cannot scroll in portrait until I flip the phone into landscape mode which fixes the scrolling issue and then I can flip the phone back to portrait mode and scroll again.

Any ideas?



Kind regards,
Eddy

**Comment by adamschwartz** [comment]
Something like https://github.com/HubSpot/vex/issues/43#issuecomment-33303954 is probably the right thing, but I can’t say for sure that your iPhone 6S issue would be solved as well.

**Pull request closed without merging**
