### PR TITLE
Check if animation properties are set on close

### PR DESCRIPTION
**Pull request by mkorablin**
Hello,

I'm proposing a check if the `$vex` object has any animation properties set to find out whether or not we need to listen to `animationEndEvent`. If animation properties are not set, `animationEndEvent` doesn't fire and the dialog doesn't close.

This has been discussed in a different PR: https://github.com/HubSpot/vex/pull/70

### CODE REVIEW

**Comment by adamschwartz** [comment]
Hey @mkorablin thanks for submitting this. I’ll try to take a look as soon as I have a spare moment. Thx

**Comment by adamschwartz** [comment]
Hey @mkorablin I’m so sorry I haven’t had the time to look into this yet. I’ll keep you posted though.

**Comment by geekjuice** [comment]
LGTM :+1: Thanks again and sorry for the delay

**Comment by geekjuice** [comment]
@adamschwartz Mind publishing to npm? or you can add me to the project on npm and help maintain it as well. Whatever works better for you :beers:

**Comment by adamschwartz** [comment]
Absolutely happy to add you. What do I need to do?

**Comment by geekjuice** [comment]
I believe you just need to run [`npm adduser ...`](https://docs.npmjs.com/cli/adduser) with the correct scopes and I can publish the project without having to bug you about it :stuck_out_tongue:

**Comment by adamschwartz** [comment]
Turned out to be `npm owner add geekjuice` but that link was helpful in finding that. :smile: 

```
± npm owner ls vex-js
adamschwartz <adam.flynn.schwartz@gmail.com>
geekjuice <nick.joosung.hwang@gmail.com>
```

I think you should now be all set.

**Comment by geekjuice** [comment]
Heh I guess that works too :+1: I'll go ahead and publish it now.

**Comment by adamschwartz** [comment]
:boom:

**Comment by adamschwartz** [comment]
@geekjuice https://github.com/HubSpot/vex/issues/142

**Pull request merged**
