### PR TITLE
Proposed update to default className

### PR DESCRIPTION
**Pull request by stephan-nordnes-eriksen**
I propose that there is a default theme selected upon start. This makes it just a little bit easier when starting using vex for a few people. In my case I use brunch to bake vex into all of my stuff. I would love to not have a setup phase for vex if I am content with the plain vex-theme-os.

### CODE REVIEW

**Comment by geekjuice** [comment]
Would it possible to make the default `vex-theme-default`? Mainly because the theme name has `default` in it? :trollface:

**Comment by stephan-nordnes-eriksen** [comment]
Would be much more :trollface: if the default theme wasn't the default theme ;)

**Comment by geekjuice** [comment]
Fair point :sweat_smile:

Let me just double check that this and https://github.com/HubSpot/vex/pull/124 works alright and I'll have them merged in ASAP.

Thanks again for these changes! :smiley_cat:

**Comment by stephan-nordnes-eriksen** [comment]
Thank you for the quick replies!

**Comment by adamschwartz** [comment]
Hey y’all, I love the spirit of this, but I want to take a step back and explain the rationale before we go ahead with it. (I’m not opposed, but I think more discussion is needed.)

First off, the idea behind breaking of `vex` from `vex.dialog` is because the thinking is that other open source libraries may want to build on `vex` due to its (hopefully) minimal/slim/efficient/to-the-point architecture.

Along this line, I always intended that the minimal code required to run the project was `vex.js` and `vex.css`, and I believe the docs make a reference to this. However, highly recommended (if not officially “required”) that one of the theme files be included when using vex dialog. With all of that in mind, I think this change might be more appropriate for the default options object in vex dialog as opposed to vex.

That being said, if we make it clear that the new minimal set of required files includes `vex.js`, `vex.css` _and_ `vex-theme-default.css`, then I would be more inclined to support this change PR as currently written.

**Comment by bbatliner** [comment]
I think having no default class name is a good check for anyone that includes vex and is wondering why the dialogs don't look good. Add a theme! Even if it is a default.

**Pull request closed without merging**
