### PR TITLE
Fixing issue with bower.json

### PR DESCRIPTION
**Pull request by stephan-nordnes-eriksen**
Globs are no longer supported by Bower.

### CODE REVIEW

**Comment by stephan-nordnes-eriksen** [comment]
This resolves issues I had with brunch not able to compile vex.

**Comment by geekjuice** [comment]
Do you think you can point to the non-minified files in the `main` field`? It's part of the spec for that field. (I not realized I did not answer that part of the question in the original issue thread :sweat_smile:)

**Comment by stephan-nordnes-eriksen** [comment]
Ahh.. I though it was the "production" files that were supposed to go in the main files. Sure. Let me fix that.

**Comment by adamschwartz** [comment]
I think the order of the files in `main` could be improved. For example, `vex.css` should maybe be listed before the theme files as a subtle suggestion that that’s the current order when including. Otherwise, lgtm. :shipit:

**Comment by stephan-nordnes-eriksen** [comment]
Done :)

**Comment by adamschwartz** [comment]
Thank you kindly :horse:

**Comment by geekjuice** [comment]
:+1:

**Pull request merged**
