### PR TITLE
Bump and build 2.3.0

### PR DESCRIPTION
**Pull request by gusvargas**
@timmfin @adamschwartz

### CODE REVIEW

**Comment by adamschwartz** [comment]
Hey Gus, I really appreciate you doing this. But I think I’d prefer 2.3.0 since #96 potentially changes behavior / adds a feature. (I think a minor version bump like this would be more appropriate for performance improvements, code cleanup, or minor bug fixes.)

**Comment by gusvargas** [comment]
Ah, you're right. Sorry about that.

**Comment by adamschwartz** [comment]
No problem!

**Comment by adamschwartz** [comment]
Created a release. https://github.com/HubSpot/vex/releases/tag/v2.3.0

**Comment by EgoAleSum** [comment]
Could you please ensure that 2.3.0 is published to NPM? thanks!

**Comment by adamschwartz** [comment]
@EgoAleSum Done.

**Pull request merged**
